# -*- coding: utf-8 -*-
"""CPproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SrH1hrHZBaPX5x1NJB4zgydvjyikxfJj
"""

from google.colab import drive
drive.mount('/content/drive')

"""from google.colab import drive: Imports the drive module from Google Colab.  
drive.mount('/content/drive'): Mounts Google Drive to the specified directory.
"""

!ls /content/drive/MyDrive/carbrand

"""!ls: Allows us to use shell commands within Colab.(komut satirlarini kullanmamizi saglar.)          
'/content/drive/MyDrive/carbrand': Specifies the car brand folder on Google Drive.(Drivedaki carbrand klasorunu belirtir.)
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

#1
train_datagen = ImageDataGenerator(rescale=1./255)
valid_datagen = ImageDataGenerator(rescale=1./255)
test_datagen  = ImageDataGenerator(rescale=1./255)

#2
train_generator = train_datagen.flow_from_directory(
    '/content/drive/MyDrive/carbrand/train',
    target_size=(224, 224),
    batch_size=32,
    class_mode='sparse'
)

#3

validation_generator = valid_datagen.flow_from_directory(
    '/content/drive/MyDrive/carbrand/valid',
    target_size=(224, 224),
    batch_size=32,
    class_mode='sparse'
)

#4

test_generator = test_datagen.flow_from_directory(
    '/content/drive/MyDrive/carbrand/test',
    target_size=(224, 224),
    batch_size=32,
    class_mode='sparse',
    shuffle=False
)

"""1-) ImageDataGenerator: A Keras class used for processing and scaling image data.(goruntu verilerini islemek ve olceklendirmek icin kullanilir.).    
rescale=1./255: Transforms pixel values from the range 0-255 to 0-1.(Piksel degerlerini 0-255 ten 0-1 e donusturur.).   

2-)Load training data,             
 -flow_from_directory: Fetches data from the specified folder.(verileri belirtilen klasorden alir.).      
- target_size=(224, 224): Adjusts the images to the input size of the model.(Goruntuleri modelin giris boyutuna uygun hale getirir.).   
- batch_size=32: Sets the number of images processed simultaneously.(Modelin ayni anda isleyecegi goruntu sayisini belirtir.).
- class_mode='sparse': Provides classification labels as indices (e.g., 0, 1, 2). (siniflarndirma etiketlerini indeks formatinda verir.).   
This structure ensures that the model receives data in a continuous flow.(bu yapi modelin veriyi duzenli bir akista almasini saglar.)

3-)Load validation data,                 
Validation data helps evaluate the model's generalization capability during training.The structure is the same as the training data loader but specifically for validation.(Doğrulama verileri, modelin eğitim sırasında genelleme yapma yeteneğini ölçmek için kullanılır.Egitimdeki yapi ile ayni ancak dogrulama verisi olarak ayrilmistir.).   

4-)Load test data,
-shuffle=False: Loads test data without shuffling to maintain the correct order.(test verilerini karistirmadan yukler, bu sayede tahmin sonuclarini dogru sirada analiz edebiliriz.).                  
-Unlike training and validation data, it is specifically used for independent accuracy measurement.(Eğitim ve doğrulama verilerinden ayrı olarak, model doğruluğunu bağımsız olarak ölçmek için kullanılır.).



"""

#1
from tensorflow.keras import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
import pandas as pd
from io import StringIO
import sys

#2
# Create Model
model = Sequential([
    Input(shape=(224, 224, 3)),
    Conv2D(32, (3,3), activation='relu', name='Conv2D_1'),
    MaxPooling2D(2,2, name='MaxPool_1'),

    Conv2D(64, (3,3), activation='relu', name='Conv2D_2'),
    MaxPooling2D(2,2, name='MaxPool_2'),

    Conv2D(128, (3,3), activation='relu', name='Conv2D_3'),
    MaxPooling2D(2,2, name='MaxPool_3'),

    Flatten(name='Flatten'),
    Dense(128, activation='relu', name='Dense_1'),
    Dropout(0.6, name='Dropout'),
    Dense(7, activation='softmax', name='Output')
])

#3


stream = StringIO()
sys.stdout = stream
model.summary()
sys.stdout = sys.__stdout__


summary_str = stream.getvalue()


summary_lines = summary_str.split('\n')


layer_info = []
for line in summary_lines[2:-4]:
    parts = line.split()
    if len(parts) >= 4:
        layer_name = parts[0]
        layer_type = parts[1]
        output_shape = ' '.join(parts[2:-1])
        num_params = parts[-1]
        layer_info.append([layer_name, layer_type, output_shape, num_params])


model_df = pd.DataFrame(layer_info, columns=['Layer Name', 'Layer Type', 'Output Shape', 'Param #'])
print("CNN Model Yapısı:")
print(model_df)

"""1-) This code block imports the necessary libraries for model building and result formatting.(Gerekli kutuphanelerin ice aktarilmasi.).      

2-)-Sequential: Used to stack layers sequentially.(Katmanlari sirayla eklemek icin.).              
-Input: Defines the input shape (224x224x3).(Modelin giris boyutu tanimlanir.).
-Conv2D: Adds convolutional layers.(Evrimsel katman ekler.), First layer has 32 filters, second has 64, third has 128.(ilk katman 32, ikinci katman 64, ucuncu katman 128 filtre kullanir.).          
-MaxPooling2D:Reduces dimensionality (2x2 pooling).(Boyut azaltma islemi.).   
-Flatten: Converts multi-dimensional data to a single dimension.(Çok boyutlu veriyi tek boyutlu hale getirir.).            
-Dense: Fully connected layer with 128 neurons.(yogun katman 128 noron icerir.).   
-Dropout: Reduces overfitting by randomly dropping 60% of neurons.(Overfittingi azaltmak icin %60 oraninda noronlari devre disi birakir.).       
-Output: Final layer with softmax activation (7 classes).(Softmax aktivasyon fonksiyonuyla çıktı katmanı (7 sınıf)).

3-)This code block formats the model summary as a table.(model ozetini tablo halinde duzenlemek icin.).         
-StringIO: Captures the model summary as text.(Model ozetini metin olarak yakalar.).           
-sys.stdout: Redirects standard output to capture.(Ciktiyi yakalamak icin standart ciktiyi degistirir.).         
-Table creation: Displays each layer as a table row.(modelin her katmanini bir tablo olarak gosterir.).


"""

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
#compile cnn

"""This code block compiles the CNN model to make it ready for training.(Bu kod bloğu, CNN modelini eğitime hazır hale getirmek için derleme işlemini yapar.).  
-optimizer='adam': Speeds up the learning process.(Modelin ogrenme surecini hizlandirir.) ,Provides more stable and faster convergence.(Daha kararli ve hizli yakinsama saglar.).                                
-Sparse Categorical Crossentropy:Ideal when the class labels are represented as integers.(Eğitim verilerimizde sınıf etiketleri 0, 1, 2, ... gibi sayılar olduğu için kullanılır..).        
-Accuracy Metric:Provides a straightforward evaluation of classification performance.(Modelin ne kadar doğru sınıflandırma yaptığını görmek için temel başarı ölçütü olarak kullanılır.).
"""

print("Model eğitilmeye başlıyor...")
history = model.fit(
    train_generator,
    epochs=3,
    validation_data=validation_generator
)
print("Model eğitildi!")

"""This code block is used to train the CNN model.(Bu kod bloğu, CNN modelini eğitmek için kullanılır.).    
-train_generator:Data generator that supplies the training data.(Eğitim verilerini sağlayan veri üreticisi.),
Feeds data to the model in the required format and initiates training.(Verileri modelin ihtiyaç duyduğu formatta sunar ve eğitimi başlatır.).     
-epochs=10:Specifies how many iterations over the entire dataset the model will perform.(Modelin eğitim sırasında veri kümesi üzerinden kaç kez geçeceğini belirtir.).    
-validation_data=validation_generator:Provides validation data to assess model performance during training. (Eğitim sırasında modelin performansını değerlendirmek için kullanılan doğrulama verisidir.), The model's generalization ability is measured after each epoch.(Model her epoch sonunda doğrulama verisi ile genelleme başarısını ölçer.).
"""

import matplotlib.pyplot as plt

#1

# Accuracy grafiği
plt.plot(history.history['accuracy'], label='Eğitim Doğruluğu')
plt.plot(history.history['val_accuracy'], label='Doğrulama Doğruluğu')
plt.xlabel('Epoch')
plt.ylabel('Doğruluk')
plt.legend()
plt.title('Eğitim ve Doğrulama Doğruluğu')
plt.show()

#2

# Loss grafiği
plt.plot(history.history['loss'], label='Eğitim Kaybı')
plt.plot(history.history['val_loss'], label='Doğrulama Kaybı')
plt.xlabel('Epoch')
plt.ylabel('Kayıp')
plt.legend()
plt.title('Eğitim ve Doğrulama Kaybı')
plt.show()

"""1-)This part is used to plot the training and validation accuracy.(Modelin egitim ve dogrulama dogrulugunu cizmek icin).
-plt.plot(): Used to create a plot.(grafik cizmek icin kullanilir.), history.history['accuracy']: Gets training accuracy values.(Egitim dogrulugu verilerini alir.), history.history['val_accuracy']: Gets validation accuracy values.(Dogrulama dogrulugu verilerini alir.).    
-plt.xlabel(): Sets the label for the X-axis (Epoch).(X ekseni basligi.).    
-plt.ylabel(): Sets the label for the Y-axis (Accuracy).(Y ekseni basligi.).     
-plt.legend(): Adds labels to the plot lines.(Grafikteki cizgileri etiketler.).  
-plt.title(): Sets the title of the graph.(Grafiğin başlığını belirler.).  
-plt.show(): Displays the graph.(Grafigi ekranda gosterir.).   

2-)This part is used to plot the training and validation loss.(modelin egitim ve dogrulama kaybini cizmek icin kullanilir.).
-plt.plot(): Plots the training and validation loss on the same graph.(egitim ve dogrulama kaybini ayni grafikte cizer.),history.history['loss']: Retrieves training loss values.(Egitim kaybini alir.),history.history['val_loss']: Retrieves validation loss values.(Dogrulama kaybini alir.).  
-plt.xlabel(): Sets the label for the X-axis (Epoch).(X ekseni basligi.).    
-plt.ylabel(): Sets the label for the Y-axis (Loss).(Y ekseni basligi.).     
-plt.legend(): Adds labels to the plot lines.(Grafikteki cizgileri etiketler.).  
-plt.title(): Sets the title of the graph.(Grafiğin başlığını belirler.).  
-plt.show(): Displays the graph.(Grafigi ekranda gosterir.).   

"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import numpy as np

#1

# Test seti üzerinden tahmin yap
test_pred = model.predict(test_generator)
test_pred_labels = np.argmax(test_pred, axis=1)

#2

# Gerçek etiketler
true_labels = test_generator.classes

#3

# Confusion Matrix oluştur
cm = confusion_matrix(true_labels, test_pred_labels)

#4

# Görselleştirme
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=test_generator.class_indices.keys())
plt.figure(figsize=(8, 8))
disp.plot(cmap='Blues')
plt.title("Confusion Matrix (Test Set)")
plt.show()

"""1-) In this step, we obtain the model predictions on the test data.(Bu adımda, modelin test verileri üzerindeki tahminlerini elde ediyoruz.).      
-model.predict(test_generator):Makes predictions on the test dataset.(test veri seti uzerinde tahmin yapilir.), The predicted values are returned as probabilities.(Tahmin edilen degerler olasilik olarak doner.).     
-np.argmax(test_pred, axis=1):Selects the maximum probability as the predicted class.(Olasılık degerlerinden en yüksek olanını secer ve sınıf etiketi olarak doner.), axis=1: Finds the maximum value in each row (sample).(her bir ornek icin maksimum degeri bulur.).   

2-)test_generator.classes:Returns the true class labels from the test data. (Test veri setindeki gerçek sınıf etiketlerini doner.), Used to compare with the model predictions.(Modelin tahminleri ile karşılaştırma yaparken kullanılır.).

3-)confusion_matrix(true_labels, test_pred_labels):Rows represent the actual labels, columns represent the predicted labels.(Satırlarda gerçek etiketler, sütunlarda tahmin edilen etiketler bulunur.), Clearly shows correct and incorrect classifications.(Dogru ve yanlis siniflandirmalari net olarak gosterir).

4-)Used to visually plot the Confusion Matrix.(Confusion Matrixi gorsellestirme)
-ConfusionMatrixDisplay:Takes the matrix data and displays it visually.(Matris verilerini alir ve gorsellestirir.), cmap='Blues': Creates a graph with blue shades.(Mavi tonlarda grafik olusturur.).
-plt.title:Adds a title to the graph.(Grafige baslik ekler.).        
-plt.show(): Displays the plot on the screen.(Grafigi ekranda gosterir.).


"""

import os
from collections import Counter

train_dir = '/content/drive/MyDrive/carbrand/train'

labels = []
for folder in os.listdir(train_dir):
    folder_path = os.path.join(train_dir, folder)
    if os.path.isdir(folder_path):
        count = len(os.listdir(folder_path))
        labels.append((folder, count))

for label, count in sorted(labels, key=lambda x: x[1], reverse=True):
    print(f"{label}: {count} görsel")

"""This loop finds each class folder within the training directory and counts the number of images inside.(Egitim veri klasorunun icindeki her sinif klasorunu bulur ve gorsel sayisini hesaplar.).
-os.listdir(train_dir):Lists all subfolders (classes) within the training directory.(Tum lat klasorleri(siniflari) listeler.).                
-os.path.join(train_dir, folder):Joins the main directory path with the subfolder name.(Ana klasor adi ve alt klasor adini birlestirir.).                
-os.path.isdir(folder_path):Selects only folder items (excludes files).(Yalnizca klasor olan ogeleri secer.).                                           
-len(os.listdir(folder_path)):Finds the number of images within the folder.(Klasordeki gorsel sayisini bulur.).                                             
-labels.append((folder, count)):Adds the folder name and image count as a tuple to the list.(Klasor ve gorsel sayisini tuple olarak listeye ekler.).               
-sorted(labels, key=lambda x: x[1], reverse=True):Sorts the classes by the number of images, in descending order.(Gorsel sayisina gore buyukten-kucuge siralar.).           
-print(f"{label}: {count} images"):Displays the class name and the number of images.(sinif adini ve gorsel sayisini ekrana yazdirir.).
"""

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

class_indices = train_generator.classes
weights = compute_class_weight(class_weight='balanced', classes=np.unique(class_indices), y=class_indices)
class_weights = dict(enumerate(weights))

print("Sınıf Ağırlıkları:", class_weights)

"""class_indices = train_generator.classes = This line fetches the class indices from the training data.(Egitim verilerindeki sinif indekslerini alir.).        
-train_generator.classes:Returns class labels from the training data generator.(Egitim verisi olusturucusundan sınıf etiketlerini dondurur.).                   
-compute_class_weight:class_weight='balanced': Balances the weights according to class distribution.(Agirliklarin dengelenmesini saglar.).                     
-classes=np.unique(class_indices): Finds unique class labels.(Farkli sinif etikletlerini belirler.).
-y=class_indices: Uses class labels from the training data generator.(Egitim verisi olusturucusundaki sınıf etiketlerini kullanır.).                          
-dict(enumerate(weights)):Converts weight values into a dictionary format.(Agirlik degerlerini sozluk formatina donusturur.), Uses class indices as keys.(Sinif indekslerini anahtar olarak kullanir.).

"""

history = model.fit(
    train_generator,
    epochs=5,
    validation_data=validation_generator,
    class_weight=class_weights,
    callbacks=[early_stop]
)

"""This code block is used for training the model.(Bu kod bloğu,  modeli eğitmek için kullanılır.).    
-train_generator:Data generator that supplies the training data.(Eğitim verilerini sağlayan veri üreticisi.),
Feeds data to the model in the required format and initiates training.(Verileri modelin ihtiyaç duyduğu formatta sunar ve eğitimi başlatır.).     
-epochs=10:Specifies how many iterations over the entire dataset the model will perform.(Modelin eğitim sırasında veri kümesi üzerinden kaç kez geçeceğini belirtir.).    
-validation_data=validation_generator:Provides validation data to assess model performance during training. (Eğitim sırasında modelin performansını değerlendirmek için kullanılan doğrulama verisidir.), The model's generalization ability is measured after each epoch.(Model her epoch sonunda doğrulama verisi ile genelleme başarısını ölçer.).                               
-class_weight=class_weights:Passes class weights to the model to handle class imbalance.(Sinif dengesizliklerini ortadan kaldirmak icin sinif agirliklarini modele aktarir.), Ensures that the model does not ignore minority classes during training.(Egitim sirasinda modelin daha az veriye sahip siniflari goz ardi etmemesini saglar.).                                                        
-callbacks=[early_stop]:Enables the early stopping mechanism during training.(Egitim sirasinda erken durdurma mekanizmasini etkinlestirir.), Stops training if no improvement in validation loss is observed.(Eger model dogrulama kaybinda bir iyilestirme gostermezse egitimi durdurur.).
"""

import matplotlib.pyplot as plt

# Doğruluk grafiği
plt.plot(history.history['accuracy'], label='Eğitim Doğruluğu')
plt.plot(history.history['val_accuracy'], label='Doğrulama Doğruluğu')
plt.xlabel('Epoch')
plt.ylabel('Doğruluk')
plt.legend()
plt.title('Eğitim ve Doğrulama Doğruluğu')
plt.grid(True)
plt.show()

# Kayıp (Loss) grafiği
plt.plot(history.history['loss'], label='Eğitim Kaybı')
plt.plot(history.history['val_loss'], label='Doğrulama Kaybı')
plt.xlabel('Epoch')
plt.ylabel('Kayıp')
plt.legend()
plt.title('Eğitim ve Doğrulama Kaybı')
plt.grid(True)
plt.show()

"""1-)This part is used to plot the training and validation accuracy.(Modelin egitim ve dogrulama dogrulugunu cizmek icin).
-plt.plot(): Used to create a plot.(grafik cizmek icin kullanilir.), history.history['accuracy']: Gets training accuracy values.(Egitim dogrulugu verilerini alir.), history.history['val_accuracy']: Gets validation accuracy values.(Dogrulama dogrulugu verilerini alir.).    
-plt.xlabel(): Sets the label for the X-axis (Epoch).(X ekseni basligi.).    
-plt.ylabel(): Sets the label for the Y-axis (Accuracy).(Y ekseni basligi.).     
-plt.legend(): Adds labels to the plot lines.(Grafikteki cizgileri etiketler.).  
-plt.title(): Sets the title of the graph.(Grafiğin başlığını belirler.).  
-plt.show(): Displays the graph.(Grafigi ekranda gosterir.).   

2-)This part is used to plot the training and validation loss.(modelin egitim ve dogrulama kaybini cizmek icin kullanilir.).
-plt.plot(): Plots the training and validation loss on the same graph.(egitim ve dogrulama kaybini ayni grafikte cizer.),history.history['loss']: Retrieves training loss values.(Egitim kaybini alir.),history.history['val_loss']: Retrieves validation loss values.(Dogrulama kaybini alir.).  
-plt.xlabel(): Sets the label for the X-axis (Epoch).(X ekseni basligi.).    
-plt.ylabel(): Sets the label for the Y-axis (Loss).(Y ekseni basligi.).     
-plt.legend(): Adds labels to the plot lines.(Grafikteki cizgileri etiketler.).  
-plt.title(): Sets the title of the graph.(Grafiğin başlığını belirler.).  
-plt.show(): Displays the graph.(Grafigi ekranda gosterir.).   

"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import numpy as np

# Test seti üzerinden tahmin yap
test_pred = model.predict(test_generator)
test_pred_labels = np.argmax(test_pred, axis=1)

# Gerçek etiketler
true_labels = test_generator.classes

# Confusion Matrix oluştur
cm = confusion_matrix(true_labels, test_pred_labels)

# Görselleştirme
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=test_generator.class_indices.keys())
plt.figure(figsize=(8, 8))
disp.plot(cmap='Blues')
plt.title("Confusion Matrix (Test Set)")
plt.show()

"""1-) In this step, we obtain the model predictions on the test data.(Bu adımda, modelin test verileri üzerindeki tahminlerini elde ediyoruz.).      
-model.predict(test_generator):Makes predictions on the test dataset.(test veri seti uzerinde tahmin yapilir.), The predicted values are returned as probabilities.(Tahmin edilen degerler olasilik olarak doner.).     
-np.argmax(test_pred, axis=1):Selects the maximum probability as the predicted class.(Olasılık degerlerinden en yüksek olanını secer ve sınıf etiketi olarak doner.), axis=1: Finds the maximum value in each row (sample).(her bir ornek icin maksimum degeri bulur.).   

2-)test_generator.classes:Returns the true class labels from the test data. (Test veri setindeki gerçek sınıf etiketlerini doner.), Used to compare with the model predictions.(Modelin tahminleri ile karşılaştırma yaparken kullanılır.).

3-)confusion_matrix(true_labels, test_pred_labels):Rows represent the actual labels, columns represent the predicted labels.(Satırlarda gerçek etiketler, sütunlarda tahmin edilen etiketler bulunur.), Clearly shows correct and incorrect classifications.(Dogru ve yanlis siniflandirmalari net olarak gosterir).

4-)Used to visually plot the Confusion Matrix.(Confusion Matrixi gorsellestirme)
-ConfusionMatrixDisplay:Takes the matrix data and displays it visually.(Matris verilerini alir ve gorsellestirir.), cmap='Blues': Creates a graph with blue shades.(Mavi tonlarda grafik olusturur.).
-plt.title:Adds a title to the graph.(Grafige baslik ekler.).        
-plt.show(): Displays the plot on the screen.(Grafigi ekranda gosterir.).


"""

from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score

# Tahminleri al
test_pred = model.predict(test_generator)
test_pred_labels = np.argmax(test_pred, axis=1)

# Gerçek etiketler
true_labels = test_generator.classes

# Accuracy
accuracy = accuracy_score(true_labels, test_pred_labels)

# Precision, Recall, F1-Score
precision = precision_score(true_labels, test_pred_labels, average='weighted')
recall = recall_score(true_labels, test_pred_labels, average='weighted')
f1 = f1_score(true_labels, test_pred_labels, average='weighted')

# Detaylı Rapor
report = classification_report(true_labels, test_pred_labels, target_names=test_generator.class_indices.keys())

print("Accuracy: {:.2f}%".format(accuracy * 100))
print("Precision: {:.2f}%".format(precision * 100))
print("Recall: {:.2f}%".format(recall * 100))
print("F1-Score: {:.2f}%".format(f1 * 100))
print("\nClassification Report:\n", report)